### ISSUE TITLE
get '/iiif/notifications' breaks on fake URLs

### ISSUE THREAD

**Issue by demery** [demery/iiif-ldn-demo#4]
When get '/iiif/notifications/?' is called, the `add_to_payload` call raises an exception when the notification `target` is a fake URI, causing action completion to fail:

https://github.com/demery/iiif-ldn-demo/blob/master/app.rb#L132

```ruby
label, payload = add_to_payload(doc, target_uri, 'sc:Range')
```

:camel:

**Comment by kelynch** [comment]
Addressed in #5 

🌵
